# FROM python:3.8

# WORKDIR /app

# COPY consumer.py .

# RUN pip install pika flask

# CMD ["python3", "consumer.py"]

FROM python:3.8

WORKDIR /app

COPY consumer.py .
COPY wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh
RUN pip install pika

CMD /wait-for-it.sh rabbitmq:5672 -- python3 consumer.py